"""Enumerate installed Steam Proton compatibility tools.

Scans every known Steam root for both:
  * Official Protons under <root>/steamapps/common/Proton *
  * User-installed tools under <root>/compatibilitytools.d/<name>/

Returns a deduped, sorted list of ProtonTool entries that the
CC launcher resolver and Settings picker consume.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from typing import Iterable


# Known mapping from official Proton dir basename to the internal alias
# Steam writes into CompatToolMapping. Steam tracks officials by these
# short slugs ("proton_9", "proton_experimental", etc.); the dir on
# disk has a different, human-readable name. Without this mapping, the
# resolver's step 2 (CompatToolMapping → ProtonTool.name) can never
# match for officials. Keep this list narrow — only well-known
# stable/beta/experimental/hotfix entries. Anything we miss falls
# through to the dir basename and step 2 simply doesn't match (the
# cascade then handles it via step 3 / step 4).
_OFFICIAL_NAME_ALIASES: dict[str, str] = {
    "Proton 10.0 (Beta)": "proton_10",
    "Proton 10.0": "proton_10",
    "Proton 9.0 (Beta)": "proton_9",
    "Proton 9.0": "proton_9",
    "Proton 8.0": "proton_8",
    "Proton 7.0": "proton_7",
    "Proton 6.3": "proton_63",
    "Proton 5.13": "proton_513",
    "Proton - Experimental": "proton_experimental",
    "Proton Experimental": "proton_experimental",
    "Proton - Hotfix": "proton_hotfix",
    "Proton Hotfix": "proton_hotfix",
}


@dataclass(frozen=True)
class ProtonTool:
    """A discovered Proton build.

    Attributes
    ----------
    name
        Internal name Steam uses to reference this tool (e.g. "proton_9",
        "proton-cachyos"). Must match the value Steam writes into
        CompatToolMapping[<appid>].name in config.vdf for cascade step 2
        to match.
    display_name
        Raw display name from the tool's compatibilitytool.vdf (or dir
        basename for officials). Preserved for diagnostic logging; the
        UI reads `nickname` instead, since some upstream tools (notably
        Proton-CachyOS) echo the dir slug here verbatim.
    nickname
        Short brand+version label for the Settings row and picker
        dialog. Generated by `_make_nickname` at enumeration time.
        Example: "Proton-CachyOS 11.0", "GE-Proton 9-26".
    proton_dir
        Absolute path to the directory containing the `proton`
        executable.
    source
        "official" (steamapps/common) or "compatibilitytools.d".
    steam_root
        Which Steam root this came from.
    version_key
        Tuple of integers extracted from the name, used for sort order.
        See `_sort_key` in `enumerate_proton_tools` for the actual rules.
    """

    name: str
    display_name: str
    nickname: str
    proton_dir: str
    source: str
    steam_root: str
    version_key: tuple[int, ...]


# Casing dictionary for brand-word tokens. Anything not in this dict
# falls back to str.title() casing. Keep this list narrow — only common
# brand-prefix tokens that title-case mangles ("cachyos" -> "Cachyos"
# without an entry).
_BRAND_CASING: dict[str, str] = {
    "cachyos": "CachyOS",
    "ge": "GE",
    "tkg": "Tkg",
    "proton": "Proton",
}


# Token patterns dropped before brand/version parsing.
# 8-digit YYYYMMDD date stamps and known architecture / runtime tags.
_DROP_TOKEN_RE = re.compile(
    r"^(?:\d{8}|slr|x86_64|amd64|i386|aarch64|win64|linux)$",
    re.IGNORECASE,
)


# Hybrid token: alphabetic prefix followed by digit(s) (e.g. "Proton9").
_HYBRID_TOKEN_RE = re.compile(r"^([A-Za-z]+)(\d.*)$")


# Pure dotted version: <digits>.<digits> (possibly more dotted parts).
_DOTTED_VERSION_RE = re.compile(r"^\d+(?:\.\d+)+$")


def _case_brand_token(token: str) -> str:
    """Apply _BRAND_CASING for known tokens, str.title() otherwise."""
    return _BRAND_CASING.get(token.lower(), token.title())


def _make_nickname(dir_name: str, vdf_display_name: str | None) -> str:
    """Generate a short human-friendly name for a Proton build.

    Two-stage strategy:
      1. If vdf_display_name is non-empty AND differs from dir_name AND
         is <= 32 characters, use it unchanged (some upstream tools
         ship a clean display_name).
      2. Otherwise parse the dir name: drop date / arch tokens,
         collect alphabetic brand tokens, then collect digit version
         tokens. Format as "<Brand> <Version>" or "<Brand>" alone.

    After parsing, truncate to 37 chars + ellipsis if the result still
    exceeds 40 characters (defensive guard for pathological names).

    Never raises. Always returns a string (possibly the dir_name
    verbatim if parsing yields nothing).
    """
    # Stage 1: trust a substantially-different VDF display name.
    if (
        vdf_display_name
        and vdf_display_name != dir_name
        and len(vdf_display_name) <= 32
    ):
        return vdf_display_name

    # Stage 2: parse the dir name.
    if not dir_name:
        return ""

    # Tokenize on -, _, and whitespace. Filter out drop patterns.
    raw_tokens = re.split(r"[-_\s]+", dir_name)
    tokens = [t for t in raw_tokens if t and not _DROP_TOKEN_RE.match(t)]
    if not tokens:
        return dir_name  # everything got dropped, defensive fallback

    brand_parts: list[str] = []
    version_parts: list[str] = []
    in_version = False

    for tok in tokens:
        if not in_version:
            # Phase A: collecting brand.
            if tok.isalpha():
                brand_parts.append(_case_brand_token(tok))
                continue
            # Hybrid token: peel off alpha prefix as brand, digit
            # suffix starts version.
            m = _HYBRID_TOKEN_RE.match(tok)
            if m:
                brand_parts.append(_case_brand_token(m.group(1)))
                version_parts.append(m.group(2))
                in_version = True
                continue
            # Token starts with a digit: switch to Phase B; reprocess.
            in_version = True
        # Phase B: collecting version.
        if tok.isdigit() or _DOTTED_VERSION_RE.match(tok):
            version_parts.append(tok)
        else:
            # Non-version token after we started — stop walking.
            break

    if not brand_parts:
        return dir_name  # no brand parsed; can't beat the original

    brand = "-".join(brand_parts)
    if version_parts:
        result = f"{brand} {'-'.join(version_parts)}"
    else:
        result = brand

    if len(result) > 40:
        result = result[:37] + "…"
    return result


def _default_roots() -> list[str]:
    # Single source of truth for the Steam roots list lives in
    # wine_runtimes (used by CC install discovery). Lazy-import to keep
    # this module independent at import time; cc_launcher imports from
    # both modules and the lazy edge keeps the dependency graph acyclic.
    from services.wine_runtimes import _STEAM_ROOTS
    return [os.path.expanduser(p) for p in _STEAM_ROOTS]


def _read_require_tool_appid(proton_dir: str) -> str | None:
    """Read the `require_tool_appid` value from a Proton's toolmanifest.vdf.

    Modern Proton builds (Proton 8+, Experimental, Proton-CachyOS, etc.)
    declare an AppID for the Steam Linux Runtime they're built against.
    Returns the appid string or None if not present.
    """
    manifest = os.path.join(proton_dir, "toolmanifest.vdf")
    try:
        with open(manifest, "r", encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return None
    m = re.search(r'"require_tool_appid"\s*"([^"]+)"', text)
    return m.group(1) if m else None


def _read_appmanifest_installdir(steam_root: str, appid: str) -> str | None:
    """Read the `installdir` field from a Steam appmanifest_<appid>.acf file."""
    manifest = os.path.join(
        steam_root, "steamapps", "appmanifest_" + appid + ".acf"
    )
    try:
        with open(manifest, "r", encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return None
    m = re.search(r'"installdir"\s*"([^"]+)"', text)
    return m.group(1) if m else None


def find_required_steam_runtime(
    proton_dir: str, steam_root: str
) -> str | None:
    """Locate the Steam Linux Runtime entry point this Proton needs.

    Modern Proton builds are compiled against a specific SLR's libc and
    library versions; outside the SLR pressure-vessel container, wine
    fails to start with no diagnostics. Steam dispatches through the
    runtime's `_v2-entry-point` script when the proton's toolmanifest
    declares `require_tool_appid`. This function reproduces that lookup
    for third-party launchers.

    Lookup chain:
      1. <proton_dir>/toolmanifest.vdf → require_tool_appid
      2. <steam_root>/steamapps/appmanifest_<appid>.acf → installdir
      3. <steam_root>/steamapps/common/<installdir>/_v2-entry-point

    Returns the absolute path to `_v2-entry-point`, or None if:
      - the Proton doesn't declare a required runtime,
      - the appmanifest is missing (runtime not installed),
      - the entry point is missing or non-executable.

    Callers should fall back to direct proton invocation when None is
    returned (older Protons that don't need the SLR will work that way).
    """
    appid = _read_require_tool_appid(proton_dir)
    if not appid:
        return None
    installdir = _read_appmanifest_installdir(steam_root, appid)
    if not installdir:
        return None
    entry = os.path.join(
        steam_root, "steamapps", "common", installdir, "_v2-entry-point"
    )
    if not os.path.isfile(entry) or not os.access(entry, os.X_OK):
        return None
    return entry


def _version_key_from_name(name: str) -> tuple[int, ...]:
    """Extract a sortable version tuple from a tool name.

    Examples:
        "Proton 9.0 (Beta)"            -> (9, 0)
        "GE-Proton9-26"                -> (9, 26)
        "Proton-CachyOS-9.0-20251214"  -> (9, 0, 20251214)
        "Proton - Experimental"        -> ()
    """
    nums = re.findall(r"\d+", name)
    return tuple(int(n) for n in nums)


def _parse_user_tool_vdf(path: str) -> tuple[str, str] | None:
    """Parse <dir>/compatibilitytool.vdf for (internal_name, display_name).

    Returns None on any error or unexpected shape.

    The file has the form:
      "compatibilitytools"
      {
        "compat_tools"
        {
          "<internal_name>"
          {
            "display_name" "<display>"
            ...
          }
        }
      }
    """
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return None
    # Locate the compat_tools block.
    m = re.search(r'"compat_tools"\s*\{', text)
    if not m:
        return None
    rest = text[m.end():]
    # First quoted key after the opening brace is the internal name.
    key_match = re.search(r'"([^"]+)"\s*\{', rest)
    if not key_match:
        return None
    internal = key_match.group(1)
    body = rest[key_match.end():]
    # display_name inside that block; tolerate any-order keys.
    disp_match = re.search(r'"display_name"\s*"([^"]*)"', body)
    display = disp_match.group(1) if disp_match else internal
    return internal, display


def _read_proton_dir_entry(
    base: str, source: str, steam_root: str
) -> ProtonTool | None:
    """Build a ProtonTool from a candidate directory, or None if invalid."""
    proton_bin = os.path.join(base, "proton")
    if not os.path.isfile(proton_bin) or not os.access(proton_bin, os.X_OK):
        return None
    dir_name = os.path.basename(base.rstrip(os.sep))
    if source == "compatibilitytools.d":
        parsed = _parse_user_tool_vdf(
            os.path.join(base, "compatibilitytool.vdf")
        )
        if parsed:
            internal, display = parsed
        else:
            internal = dir_name
            display = dir_name
    else:
        # official
        internal = _OFFICIAL_NAME_ALIASES.get(dir_name)
        if internal is None:
            # Spec §3.1 envisioned parsing toolmanifest.vdf for the official
            # alias, but for now we use a hardcoded dict. When Valve ships a
            # new Proton not in the dict, log so the maintainer knows to
            # extend _OFFICIAL_NAME_ALIASES. Cascade step 2 won't match this
            # tool against Steam's CompatToolMapping until then; step 3
            # (config_info) still handles it correctly.
            print(f"[CCLauncher] unknown official Proton dir {dir_name!r}; "
                  f"CompatToolMapping match for this tool will not work "
                  f"until _OFFICIAL_NAME_ALIASES is extended")
            internal = dir_name
        display = dir_name
    # Pass VDF display only when it differs from the dir basename;
    # otherwise _make_nickname has no useful hint and goes to Stage 2.
    vdf_hint = display if display != dir_name else None
    return ProtonTool(
        name=internal,
        display_name=display,
        nickname=_make_nickname(dir_name, vdf_hint),
        proton_dir=base,
        source=source,
        steam_root=steam_root,
        version_key=_version_key_from_name(dir_name),
    )


def enumerate_proton_tools(
    steam_roots: Iterable[str] | None = None,
) -> list[ProtonTool]:
    """Scan Steam roots for installed Proton builds.

    Returns
    -------
    list[ProtonTool]
        Deduped and sorted. Dedup keys on realpath of the `proton`
        binary — first-seen wins (root priority: native → .steam/steam
        → flatpak). Sort: user-installed before official; within each
        group, newest first by version_key, then mtime descending.

    Never raises. Roots that don't exist are skipped silently.
    """
    roots = list(steam_roots) if steam_roots is not None else _default_roots()
    found: list[ProtonTool] = []
    seen: set[str] = set()
    for root in roots:
        if not os.path.isdir(root):
            continue
        # User-installed tools.
        ctd = os.path.join(root, "compatibilitytools.d")
        if os.path.isdir(ctd):
            for entry in sorted(os.listdir(ctd)):
                base = os.path.join(ctd, entry)
                if not os.path.isdir(base):
                    continue
                tool = _read_proton_dir_entry(base, "compatibilitytools.d", root)
                if tool is None:
                    continue
                real = os.path.realpath(os.path.join(tool.proton_dir, "proton"))
                if real in seen:
                    continue
                seen.add(real)
                found.append(tool)
        # Official Protons.
        common = os.path.join(root, "steamapps", "common")
        if os.path.isdir(common):
            for entry in sorted(os.listdir(common)):
                if not entry.startswith("Proton"):
                    continue
                base = os.path.join(common, entry)
                if not os.path.isdir(base):
                    continue
                tool = _read_proton_dir_entry(base, "official", root)
                if tool is None:
                    continue
                real = os.path.realpath(os.path.join(tool.proton_dir, "proton"))
                if real in seen:
                    continue
                seen.add(real)
                found.append(tool)

    def _mtime(p: ProtonTool) -> float:
        try:
            return os.path.getmtime(os.path.join(p.proton_dir, "proton"))
        except OSError:
            return 0.0

    def _sort_key(p: ProtonTool) -> tuple:
        group_rank = 0 if p.source == "compatibilitytools.d" else 1
        # Tools with no parseable version (e.g. "Proton - Experimental")
        # have an empty version_key. Push them to the bottom of their
        # group via has_version=1 so they tiebreak on mtime alone, not
        # the (incorrect) "empty tuple sorts first" Python default.
        has_version = 0 if p.version_key else 1
        # Pad to a fixed length so longer tuples (more specific, e.g.
        # date-suffixed builds like Proton-CachyOS-9.0-20251214) sort
        # BEFORE shorter ones with the same prefix. Without padding,
        # tuple lex-compare puts shorter tuples first, which is
        # backwards from "newest first."
        padded = (p.version_key + (0,) * 6)[:6]
        neg_version = tuple(-n for n in padded)
        return (group_rank, has_version, neg_version, -_mtime(p))

    found.sort(key=_sort_key)
    return found
